"""widen audit_log rate-limit index to include ip_address

Revision ID: 2ff76f9b98e2
Revises: d741a58b92f1
Create Date: 2026-07-29 15:08:27.961618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ff76f9b98e2'
down_revision: Union[str, None] = 'd741a58b92f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_log_identifier_action_created'), table_name='audit_log')
    op.create_index('ix_audit_log_ip_identifier_action_created', 'audit_log', ['ip_address', 'attempted_identifier', 'action', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_log_ip_identifier_action_created', table_name='audit_log')
    op.create_index(op.f('ix_audit_log_identifier_action_created'), 'audit_log', ['attempted_identifier', 'action', 'created_at'], unique=False)
    # ### end Alembic commands ###
