"""notifications and waitlist entries

Revision ID: 499aef4dbda6
Revises: 7b85f11d2f86
Create Date: 2026-07-11 09:50:45.737301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '499aef4dbda6'
down_revision: Union[str, None] = '7b85f11d2f86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waitlist_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('attending_id', sa.Uuid(), nullable=True),
    sa.Column('room_id', sa.Uuid(), nullable=True),
    sa.Column('equipment_id', sa.Uuid(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('active', 'notified', 'cancelled', name='waitlist_status_enum'), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_time > start_time', name='ck_waitlist_entries_time_order'),
    sa.ForeignKeyConstraint(['attending_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waitlist_entries_attending_id'), 'waitlist_entries', ['attending_id'], unique=False)
    op.create_index(op.f('ix_waitlist_entries_equipment_id'), 'waitlist_entries', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_waitlist_entries_patient_id'), 'waitlist_entries', ['patient_id'], unique=False)
    op.create_index(op.f('ix_waitlist_entries_room_id'), 'waitlist_entries', ['room_id'], unique=False)
    op.create_index(op.f('ix_waitlist_entries_student_id'), 'waitlist_entries', ['student_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recipient_user_id', sa.Uuid(), nullable=True),
    sa.Column('recipient_patient_id', sa.Uuid(), nullable=True),
    sa.Column('notification_type', sa.Enum('appointment_reminder', 'appointment_expired', 'waitlist_slot_available', name='notification_type_enum'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('related_appointment_id', sa.Uuid(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(recipient_user_id IS NOT NULL) != (recipient_patient_id IS NOT NULL)', name='ck_notifications_exactly_one_recipient'),
    sa.ForeignKeyConstraint(['recipient_patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['related_appointment_id'], ['appointments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_recipient_patient_id'), 'notifications', ['recipient_patient_id'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_user_id'), 'notifications', ['recipient_user_id'], unique=False)
    op.create_index(op.f('ix_notifications_related_appointment_id'), 'notifications', ['related_appointment_id'], unique=False)
    op.add_column('appointments', sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'reminder_sent_at')
    op.drop_index(op.f('ix_notifications_related_appointment_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_patient_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_waitlist_entries_student_id'), table_name='waitlist_entries')
    op.drop_index(op.f('ix_waitlist_entries_room_id'), table_name='waitlist_entries')
    op.drop_index(op.f('ix_waitlist_entries_patient_id'), table_name='waitlist_entries')
    op.drop_index(op.f('ix_waitlist_entries_equipment_id'), table_name='waitlist_entries')
    op.drop_index(op.f('ix_waitlist_entries_attending_id'), table_name='waitlist_entries')
    op.drop_table('waitlist_entries')
    sa.Enum(name='notification_type_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='waitlist_status_enum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
