"""drop student_availability table

Revision ID: 5074bc3483b8
Revises: 8c1192899eb3
Create Date: 2026-07-14 19:35:09.439692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5074bc3483b8'
down_revision: Union[str, None] = '8c1192899eb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_availability_student_id'), table_name='student_availability')
    op.drop_table('student_availability')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_availability',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('day_of_week', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('end_time > start_time', name=op.f('ck_availability_time_order')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('student_availability_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('student_availability_pkey'))
    )
    op.create_index(op.f('ix_student_availability_student_id'), 'student_availability', ['student_id'], unique=False)
    # ### end Alembic commands ###
