"""add ordering sequence to notifications

Revision ID: 512e69ee997a
Revises: 499aef4dbda6
Create Date: 2026-07-11 09:56:44.274551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '512e69ee997a'
down_revision: Union[str, None] = '499aef4dbda6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('sequence', sa.BigInteger(), sa.Identity(always=False), nullable=False))
    op.create_unique_constraint('uq_notifications_sequence', 'notifications', ['sequence'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_notifications_sequence', 'notifications', type_='unique')
    op.drop_column('notifications', 'sequence')
    # ### end Alembic commands ###
