"""rooms equipment appointments student_availability preferred_time_of_day

Revision ID: 7b85f11d2f86
Revises: a5261183364c
Create Date: 2026-07-10 23:33:29.264220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b85f11d2f86'
down_revision: Union[str, None] = 'a5261183364c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Required for GiST exclusion constraints over plain-equality (UUID)
    # columns combined with a tstzrange overlap check.
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('equipment_type', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rooms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('student_availability',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_time > start_time', name='ck_availability_time_order'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_availability_student_id'), 'student_availability', ['student_id'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('attending_id', sa.Uuid(), nullable=True),
    sa.Column('room_id', sa.Uuid(), nullable=True),
    sa.Column('equipment_id', sa.Uuid(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('proposed', 'awaiting_confirmation', 'confirmed', 'cancelled', 'completed', 'no_show', 'rescheduling_requested', name='appointment_status_enum'), nullable=False),
    sa.Column('student_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attending_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    postgresql.ExcludeConstraint((sa.column('attending_id'), '='), (sa.text('tstzrange(start_time, end_time)'), '&&'), where=sa.text("attending_id IS NOT NULL AND status IN ('awaiting_confirmation', 'confirmed', 'rescheduling_requested')"), using='gist', name='ex_appointments_attending_overlap'),
    postgresql.ExcludeConstraint((sa.column('equipment_id'), '='), (sa.text('tstzrange(start_time, end_time)'), '&&'), where=sa.text("equipment_id IS NOT NULL AND status IN ('awaiting_confirmation', 'confirmed', 'rescheduling_requested')"), using='gist', name='ex_appointments_equipment_overlap'),
    postgresql.ExcludeConstraint((sa.column('patient_id'), '='), (sa.text('tstzrange(start_time, end_time)'), '&&'), where=sa.text("status IN ('awaiting_confirmation', 'confirmed', 'rescheduling_requested')"), using='gist', name='ex_appointments_patient_overlap'),
    postgresql.ExcludeConstraint((sa.column('room_id'), '='), (sa.text('tstzrange(start_time, end_time)'), '&&'), where=sa.text("room_id IS NOT NULL AND status IN ('awaiting_confirmation', 'confirmed', 'rescheduling_requested')"), using='gist', name='ex_appointments_room_overlap'),
    postgresql.ExcludeConstraint((sa.column('student_id'), '='), (sa.text('tstzrange(start_time, end_time)'), '&&'), where=sa.text("status IN ('awaiting_confirmation', 'confirmed', 'rescheduling_requested')"), using='gist', name='ex_appointments_student_overlap'),
    sa.CheckConstraint('end_time > start_time', name='ck_appointments_time_order'),
    sa.ForeignKeyConstraint(['attending_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_attending_id'), 'appointments', ['attending_id'], unique=False)
    op.create_index(op.f('ix_appointments_equipment_id'), 'appointments', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_room_id'), 'appointments', ['room_id'], unique=False)
    op.create_index(op.f('ix_appointments_start_time'), 'appointments', ['start_time'], unique=False)
    op.create_index(op.f('ix_appointments_student_id'), 'appointments', ['student_id'], unique=False)
    # `op.add_column` with an Enum type does not reliably auto-create the
    # Postgres enum type first (unlike op.create_table) - create it explicitly.
    sa.Enum('morning', 'afternoon', 'evening', name='preferred_time_of_day_enum').create(
        op.get_bind(), checkfirst=True
    )
    op.add_column(
        'patients',
        sa.Column(
            'preferred_time_of_day',
            sa.Enum('morning', 'afternoon', 'evening', name='preferred_time_of_day_enum'),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'preferred_time_of_day')
    op.drop_index(op.f('ix_appointments_student_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_start_time'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_room_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_equipment_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_attending_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_student_availability_student_id'), table_name='student_availability')
    op.drop_table('student_availability')
    op.drop_table('rooms')
    op.drop_table('equipment')
    # ### end Alembic commands ###
    sa.Enum(name='appointment_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='preferred_time_of_day_enum').drop(op.get_bind(), checkfirst=True)
