"""add scheduled deactivation to rooms and equipment

Revision ID: 8c1192899eb3
Revises: d7356797b4cd
Create Date: 2026-07-13 12:38:15.241006

Also adds the `resource_deactivated` NotificationType value -- autogenerate
doesn't detect new enum values on its own (same as the role_enum/
notification_type_enum additions in c29f7803b629), so that's added by hand.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c1192899eb3'
down_revision: Union[str, None] = 'd7356797b4cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('inactive_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('rooms', sa.Column('inactive_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###
    op.execute("ALTER TYPE notification_type_enum ADD VALUE IF NOT EXISTS 'resource_deactivated'")


def downgrade() -> None:
    # Note: the notification_type_enum value added in upgrade() is NOT
    # removed here -- Postgres has no `DROP VALUE` for enum types, same
    # accepted limitation as c29f7803b629.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'inactive_until')
    op.drop_column('equipment', 'inactive_until')
    # ### end Alembic commands ###
