"""direct messages

Revision ID: a9ef970f80fd
Revises: d051c6feb47e
Create Date: 2026-07-11 10:49:50.688595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9ef970f80fd'
down_revision: Union[str, None] = 'd051c6feb47e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direct_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('sender_user_id', sa.Uuid(), nullable=True),
    sa.Column('sender_patient_id', sa.Uuid(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sequence', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(sender_user_id IS NOT NULL) != (sender_patient_id IS NOT NULL)', name='ck_direct_messages_exactly_one_sender'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['sender_patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequence', name='uq_direct_messages_sequence')
    )
    op.create_index(op.f('ix_direct_messages_patient_id'), 'direct_messages', ['patient_id'], unique=False)
    op.create_index(op.f('ix_direct_messages_sender_patient_id'), 'direct_messages', ['sender_patient_id'], unique=False)
    op.create_index(op.f('ix_direct_messages_sender_user_id'), 'direct_messages', ['sender_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_direct_messages_sender_user_id'), table_name='direct_messages')
    op.drop_index(op.f('ix_direct_messages_sender_patient_id'), table_name='direct_messages')
    op.drop_index(op.f('ix_direct_messages_patient_id'), table_name='direct_messages')
    op.drop_table('direct_messages')
    # ### end Alembic commands ###
