"""add waitlist entry sequence for deterministic promotion ordering

Revision ID: aa01f3e9fe1c
Revises: c9249d86cf88
Create Date: 2026-07-14 22:47:23.387496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa01f3e9fe1c'
down_revision: Union[str, None] = 'c9249d86cf88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waitlist_entries', sa.Column('sequence', sa.BigInteger(), sa.Identity(always=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waitlist_entries', 'sequence')
    # ### end Alembic commands ###
