"""forum posts comments and votes

Revision ID: d051c6feb47e
Revises: 512e69ee997a
Create Date: 2026-07-11 10:38:04.197655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd051c6feb47e'
down_revision: Union[str, None] = '512e69ee997a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forum_posts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('author_student_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forum_posts_author_student_id'), 'forum_posts', ['author_student_id'], unique=False)
    op.create_table('forum_comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('author_student_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['forum_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forum_comments_author_student_id'), 'forum_comments', ['author_student_id'], unique=False)
    op.create_index(op.f('ix_forum_comments_post_id'), 'forum_comments', ['post_id'], unique=False)
    op.create_table('forum_post_votes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('value IN (1, -1)', name='ck_forum_post_votes_value'),
    sa.ForeignKeyConstraint(['post_id'], ['forum_posts.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'student_id', name='uq_forum_post_votes_post_student')
    )
    op.create_index(op.f('ix_forum_post_votes_post_id'), 'forum_post_votes', ['post_id'], unique=False)
    op.create_index(op.f('ix_forum_post_votes_student_id'), 'forum_post_votes', ['student_id'], unique=False)
    op.create_table('forum_comment_votes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('comment_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('value IN (1, -1)', name='ck_forum_comment_votes_value'),
    sa.ForeignKeyConstraint(['comment_id'], ['forum_comments.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_id', 'student_id', name='uq_forum_comment_votes_comment_student')
    )
    op.create_index(op.f('ix_forum_comment_votes_comment_id'), 'forum_comment_votes', ['comment_id'], unique=False)
    op.create_index(op.f('ix_forum_comment_votes_student_id'), 'forum_comment_votes', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forum_comment_votes_student_id'), table_name='forum_comment_votes')
    op.drop_index(op.f('ix_forum_comment_votes_comment_id'), table_name='forum_comment_votes')
    op.drop_table('forum_comment_votes')
    op.drop_index(op.f('ix_forum_post_votes_student_id'), table_name='forum_post_votes')
    op.drop_index(op.f('ix_forum_post_votes_post_id'), table_name='forum_post_votes')
    op.drop_table('forum_post_votes')
    op.drop_index(op.f('ix_forum_comments_post_id'), table_name='forum_comments')
    op.drop_index(op.f('ix_forum_comments_author_student_id'), table_name='forum_comments')
    op.drop_table('forum_comments')
    op.drop_index(op.f('ix_forum_posts_author_student_id'), table_name='forum_posts')
    op.drop_table('forum_posts')
    # ### end Alembic commands ###
