"""index waitlist_entries status/start_time and add sequence unique constraint

Revision ID: d741a58b92f1
Revises: f2ba3a9ee087
Create Date: 2026-07-29 15:07:18.543017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd741a58b92f1'
down_revision: Union[str, None] = 'f2ba3a9ee087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_waitlist_entries_status_start_time', 'waitlist_entries', ['status', 'start_time'], unique=False)
    op.create_unique_constraint('uq_waitlist_entries_sequence', 'waitlist_entries', ['sequence'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_waitlist_entries_sequence', 'waitlist_entries', type_='unique')
    op.drop_index('ix_waitlist_entries_status_start_time', table_name='waitlist_entries')
    # ### end Alembic commands ###
