"""add related_patient_id to notifications

Revision ID: dcd36550ac3d
Revises: f3a8c1d92b4e
Create Date: 2026-08-01 19:51:26.825951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcd36550ac3d'
down_revision: Union[str, None] = 'f3a8c1d92b4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('related_patient_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_notifications_related_patient_id'), 'notifications', ['related_patient_id'], unique=False)
    # Named explicitly (autogenerate left this `None`, which Postgres
    # accepts on create by auto-naming it -- but the matching downgrade
    # then has no real name to drop_constraint by and fails outright).
    op.create_foreign_key(
        op.f('notifications_related_patient_id_fkey'),
        'notifications', 'users', ['related_patient_id'], ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f('notifications_related_patient_id_fkey'), 'notifications', type_='foreignkey'
    )
    op.drop_index(op.f('ix_notifications_related_patient_id'), table_name='notifications')
    op.drop_column('notifications', 'related_patient_id')
    # ### end Alembic commands ###
