"""add last_read_sequence to conversation_participants

Revision ID: e38fbd1063d6
Revises: 7b6dc683b169
Create Date: 2026-08-01 22:22:26.656383

Unread-message comparisons previously mixed Message.created_at (Postgres
transaction clock) against ConversationParticipant.last_read_at (this API
server's Python clock) -- two different clock sources for the exact tie
class Message.sequence exists to avoid. This column mirrors that high-water
mark as a sequence value instead, set alongside last_read_at (which stays,
unchanged, as the display timestamp exposed via ReadReceiptOut).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e38fbd1063d6'
down_revision: Union[str, None] = '7b6dc683b169'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_participants', sa.Column('last_read_sequence', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_participants', 'last_read_sequence')
    # ### end Alembic commands ###
