"""add content_source to reports

Revision ID: ec74fe015699
Revises: 2ff76f9b98e2
Create Date: 2026-07-29 17:45:55.131120

Lets a viewer tell a real model-narrated report apart from the
deterministic plain-English fallback, a genuinely unsupported ad-hoc
question, or the assistant being unreachable entirely -- not just a
boolean "was it AI-generated". `server_default='ai'` for existing rows is
a reasonable approximation, not a real regression either way -- the field
didn't exist before this.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec74fe015699'
down_revision: Union[str, None] = '2ff76f9b98e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # `op.add_column` with an Enum type does not reliably auto-create the
    # Postgres enum type first (unlike op.create_table) - create it explicitly.
    sa.Enum(
        'ai', 'fallback_summary', 'unsupported', 'unavailable', name='report_content_source_enum'
    ).create(op.get_bind(), checkfirst=True)
    op.add_column(
        'reports',
        sa.Column(
            'content_source',
            sa.Enum(
                'ai', 'fallback_summary', 'unsupported', 'unavailable',
                name='report_content_source_enum',
            ),
            server_default=sa.text("'ai'"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'content_source')
    sa.Enum(name='report_content_source_enum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
