"""add appointment end_time and audit_log rate-limit indexes

Revision ID: efa806e13ae2
Revises: 626b8b088b7d
Create Date: 2026-07-11 20:45:05.444405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efa806e13ae2'
down_revision: Union[str, None] = '626b8b088b7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_appointments_end_time'), 'appointments', ['end_time'], unique=False)
    op.create_index('ix_audit_log_identifier_action_created', 'audit_log', ['attempted_identifier', 'action', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_log_identifier_action_created', table_name='audit_log')
    op.drop_index(op.f('ix_appointments_end_time'), table_name='appointments')
    # ### end Alembic commands ###
